name: Code Checks

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    # Ref: https://github.com/pre-commit/action
    - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v6
    - name: Install latest version of uv and set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: "true"
    - name: Install dependencies (including test group)
      run: uv sync --extra test
    - name: Display the project's dependency tree (including information on outdated packages)
      run: uv tree --outdated
    - name: Run Checking Mechanisms
      run: make check
